package Defaults;

public class Enums {
	
	public enum Status {
		Empty, Start, Finish, Blocked, inOpenList, inClosedList,Path;
	}
	public static enum Direction {
		LEFT_RIGHT, RIGHT_LEFT ,DOWN_TOP,TOP_DOWN,
		TOPLEFT_DOWNRIGHT,DOWNRIGHT_TOPLEFT,DOWNLEFT_TOPRIGHT,TOPRIGHT_DOWNLEFT,
		LEFT_TOP,TOP_LEFT,
		LEFT_DOWN,DOWN_LEFT,
		TOP_RIGHT,RIGHT_TOP,
		RIGHT_DOWN,DOWN_RIGHT,
		CENTER_TOP,CENTER_DOWN,CENTER_LEFT	,CENTER_RIGHT,
		TOP_CENTER,DOWN_CENTER,LEFT_CENTER	,RIGHT_CENTER,
		CENTER_TOPLEFT,CENTER_TOPRIGHT,CENTER_DOWNRIGHT, CENTER_DOWNLEFT,
		TOPLEFT_CENTER,TOPRIGHT_CENTER,DOWNRIGHT_CENTER, DOWNLEFT_CENTER,
		TOP_TOPLEFT,TOP_DOWNLEFT,TOP_DOWNRIGHT,TOP_TOPRIGHT,
		TOPLEFT_TOP,DOWNLEFT_TOP,DOWNRIGHT_TOP,TOPRIGHT_TOP,
		DOWN_DOWNLEFT,DOWN_TOPLEFT,DOWN_TOPRIGHT,DOWN_DOWNRIGHT,
		DOWNLEFT_DOWN,TOPLEFT_DOWN,TOPRIGHT_DOWN,DOWNRIGHT_DOWN,
		LEFT_TOPLEFT,LEFT_TOPRIGHT,LEFT_DOWNRIGHT,LEFT_DOWNLEFT,
		TOPLEFT_LEFT,TOPRIGHT_LEFT,DOWNRIGHT_LEFT,DOWNLEFT_LEFT,
		RIGHT_TOPRIGHT,RIGHT_TOPLEFT,RIGHT_DOWNLEFT,RIGHT_DOWNRIGHT,
		TOPRIGHT_RIGHT,TOPLEFT_RIGHT,DOWNLEFT_RIGHT,DOWNRIGHT_RIGHT;
	}


}
